### ISSUE TITLE
As an user I should be able to see all bloggers, post and rate & comment

### ISSUE THREAD

**Issue by BaiGanio** [BaiGanio/baiganio.github.io#36]
- [ ] Should be able to preview single blogger
- [ ] Should be able to preview blogger posts
- [ ]  Should be able to preview single post
- [ ] Should be able to share post on Facebook
_If logged:_
- [ ] Should be able to rate post 
- [ ] Should be able to comment on post
