### ISSUE TITLE
 As a blogger I should be able to CRUD on my own posts and see additional data

### ISSUE THREAD

**Issue by BaiGanio** [BaiGanio/baiganio.github.io#37]
Blogger should be able to:
- [ ] CRUD on post
- [ ] Select which post is publically visible
- [ ] Comment on post
- [ ] See post comments
- [ ] See post total stars and when star is rated
