### ISSUE TITLE
As a system I should be able to show list of videos

### ISSUE THREAD

**Issue by BaiGanio** [BaiGanio/baiganio.github.io#40]
As a system I should be able to:
- [ ] Show list of YouTube videos
- [ ] Allow the user to search for video by name
- [ ] Allow the user to rate video
- [ ] Allow the user to share video on Facebook
